### ISSUE TITLE
Regenerate Wrapper files

### ISSUE THREAD

**Issue by kayveesin** [lukhnos/lucenestudy#3]
Hi, first of all kudos for this excellent project. This thing has a huge potential to grow since there are not many projects out there like this.
I need to regenerate the java wrapper files (Document.java, Indexer.java...) in objC to add some features like stemming words, slope search settings etc. Is it possible to do that in xcode?

**Comment by lukhnos** [comment]
Your question is a bit unclear. If you meant you want to add features to the Java code, and derive an Objective-C version of it, I don't see a reason why it's impossible.

Most of Mobile Lucene is translatable to Objective-C, and that includes the majority of the analyzers and the classic query parser in its entirety. You still have to figure out a way on your own to build your own code, including using J2ObjC to translate both Mobile Lucene and your Lucene client code to Objective-C, then build them in Xcode, though.
