### ISSUE TITLE
Want to add your project to my project 

### ISSUE THREAD

**Issue by rachidlaborantin** [lukhnos/lucenestudy#4]
I want to use your project in my project but I don't know the exact dependencies
Please give me a Gradle dependencies to work with

**Comment by lukhnos** [comment]
I'm afraid that I don't plan to work on this project further. You'll want to check out the [mobile branch](https://github.com/lukhnos/lucenestudy/tree/mobile) and there are all the prebuilt JARs in its [libs](https://github.com/lukhnos/lucenestudy/tree/mobile/libs) directory. You can simply copy those JARs to where your project lives and set up Gradle to use those pre-built JARs accordingly.
